const express = require('express');
const authRoute = require('./auth.route');
const userRoute = require('./user.route');
const docsRoute = require('./docs.route');
const productRoute = require('./products.route');
const filtersRoute = require('./filters.route');
const sleasList = require('./salesList.route');
const inventoryRoute = require('./inventory.route');
const vendorRoute = require('./vendor.route');
const partyRoute = require('./party.route');
const stockOutRoute = require('./stockOut.route');
const omsRoute = require('./oms.route');
const jobCardRoute = require('./jobCard.route');
const designRoute = require('./design.route');
const analyticsRoute = require('./analytics.route');
const myntraRoute = require('./myntra.route');
const returnsRoute = require('./returns.route');
const printConfigRoute = require('./printConfig.route');
const departmentReportRoute = require('./departmentReport.route');
const chatTaskRoute = require('./chatTask.route');

const router = express.Router();

router.use('/auth', authRoute);
router.use('/users', userRoute);
router.use('/upload', require('./upload.route'));
router.use('/docs', docsRoute);
router.use('/products', productRoute);
router.use('/filters_value', filtersRoute);
router.use('/salesList', sleasList);
router.use('/inventory', inventoryRoute);
router.use('/vendor', vendorRoute);
router.use('/party', partyRoute);
router.use('/stockOut', stockOutRoute);
router.use('/oms', omsRoute);
router.use('/jobCards', jobCardRoute);
router.use('/designs', designRoute);
router.use('/analytics', analyticsRoute);
router.use('/myntra', myntraRoute);
router.use('/returns', returnsRoute);
router.use('/print-config', printConfigRoute);
router.use('/department-reports', departmentReportRoute);
router.use('/workspace', chatTaskRoute);
router.use('/fabric-vendors', require('./fabricVendor.route'));
router.use('/fabric', require('./fabric.route'));
router.use('/fabric-challan', require('./fabricChallan.route'));
router.use('/raw-materials', require('./rawMaterial.route'));
router.use('/infra-bills', require('./infrastructureBill.route'));

module.exports = router;
